// ==========================================
// 1. قاموس الترجمات الشامل (AR / EN)
// ==========================================
const translations = {
    ar: {
        home: "الرئيسية",
        services: "الخدمات",
        strategies: "استراتيجيات التسويق",
        web: "تصميم المواقع",
        media: "الانتاج والإبداع",
        ads: "الإعلانات",
        data: "تحليل البيانات",
        hero_title: "Storm Agency",
        hero_tagline: "شريكك الأمثل في بناء العلامة التجارية والتسويق الرقمي",
        services_title: "خدماتنا",
        strategies_title: "بناء استراتيجيات وخطط تسويقية",
        strategies_desc: "نعمل على بناء استراتيجيات تسويقية متكاملة تساعد عملاءك على الوصول لجمهورهم المستهدف وتحقيق أهدافهم التسويقية",
        web_title: "تصميم وتطوير المواقع وحمايتها الإلكترونية",
        web_desc: "نصمم ونطور مواقع احترافية سريعة وآمنة بتجربة مستخدم مميزة تعكس هوية علامتك التجارية",
        media_title: "تصوير وإنتاج وجرافيك ديزاين",
        media_desc: "نقدم خدمات تصوير احترافية وإنتاج محتوى مرئي مبدع يجذب انتباه الجمهور ويعكس جودة علامتك التجارية",
        ads_title: "الإعلانات",
        ads_desc: "نخطط وننفذ حملات إعلانية فعالة على جميع المنصات لتحقيق أقصى عائد على استثمارك الإعلاني",
        data_title: "تحليل البيانات",
        data_desc: "نحلل بيانات حملاتك وسلوك جمهورك لاتخاذ قرارات تسويقية مدروسة وتحسين أداء حملاتك باستمرار",
        view_work: "اعملنا",
        about_title: "من نحن",
        about_desc: "Storm Agency هي وكالة تسويق وإعلانات رائدة تقدم حلولاً تسويقية شاملة للشركات والعلامات التجارية",
        contact_title: "تواصل معنا",
        footer: "© 2026 Storm Agency. جميع الحقوق محفوظة",
        read_more: "اقرأ المزيد",
        whatsapp: "تواصل واتساب",
        follow_us: "تابعنا",
        strategies_1: "تحليل السوق والمنافسين",
        strategies_1_desc: "دراسة شاملة لمتطلبات السوق وسلوك المنافسين",
        strategies_2: "وضع خطة تسويقية",
        strategies_2_desc: "تحديد الأهداف والاستراتيجيات والقنوات التسويقية المناسبة",
        strategies_3: "إدارة الحملات",
        strategies_3_desc: "تنفيذ ومتابعة الحملات التسويقية وقياس الأداء",
        web_1: "تصميم UI/UX",
        web_1_desc: "واجهات مستخدم جذابة وسهلة الاستخدام",
        web_2: "تطوير الموقع",
        web_2_desc: "برمجة الموقع بأحدث التقنيات وأعلى معايير الجودة",
        web_3: "الأمان والحماية",
        web_3_desc: "حماية الموقع من الاختراقات والتهديدات الإلكترونية",
        media_1: "التصوير الاحترافي",
        media_1_desc: "تصوير منتجات وأعمال بجودة عالية",
        media_2: "الإنتاج المرئي",
        media_2_desc: "إنتاج فيديوهات وإعلانات مرئية مبدعة",
        media_3: "التصميم الجرافيكي",
        media_3_desc: "تصميم هويات بصرية ومطبوعات احترافية",
        ads_1: "إعلانات جوجل",
        ads_1_desc: "حملات إعلانية على شبكة البحث والعرض",
        ads_2: "إعلانات السوشيال ميديا",
        ads_2_desc: "إعلانات مستهدفة على فيسبوك وإنستجرام وتويتر",
        ads_3: "إعلانات الفيديو",
        ads_3_desc: "إنتاج ونشر إعلانات فيديو جذابة",
        data_1: "تحليل المواقع",
        data_1_desc: "قياس أداء الموقع وسلوك الزوار",
        data_2: "تحليل الحملات",
        data_2_desc: "تقييم عائد الاستثمار على الحملات الإعلانية",
        data_3: "التقارير والمراجعات",
        data_3_desc: "تقارير مفصلة وتمارين تحسين مستمرة",
        word1: "استراتيجية",
        word2: "إبداع",
        word3: "تسويق",
        word4: "تصميم",
        word5: "تحليل",
        word6: "إعلان",
        word7: "رقمي",
        word8: "نجاح",
        portfolio_subtitle: "نماذج من أعمالنا المتميزة",
        portfolio_desc: "نماذج من أعمالنا المتميزة التي نفخر بها. نعمل بشغف وإبداع لتقديم أفضل الحلول التسويقية لعملائنا.",
        all_work: "جميع أعمالنا",
        view_all: "عرض جميع الأعمال",
        cta_consultation: "احصل على استشارتك المجانية",
        stats_budget_desc: "ميزانيات إعلانية مُدارة بنجاح",
        stats_campaigns_desc: "حملة إعلانية ناجحة",
        stats_impressions_desc: "انطباع وظهور إعلاني",
        stats_messages_desc: "محادثة واستفسار مباشر",
        partners_title: "شركاء النجاح",
        scanner_title: "فحص أمان المواقع",
        scanner_desc: "فحص شامل للمواقع لاكتشاف الثغرات الأمنية",
        results_arsenal_title: "ترسانة النتائج",
        results_arsenal_desc: "أدوات ذكية مجانية لفحص أمان موقعك، تحليل إعلاناتك، كتابة هوكات الريلز، وزيادة مبيعاتك.",
        back_to_home: "العودة للرئيسية",
        arsenal_header_desc: "أدوات ذكية مجانية لفحص أمان موقعك، تحليل إعلاناتك، كتابة هوكات الريلز، وزيادة مبيعاتك.",
        sec_card_title: "فحص أمان المواقع",
        sec_card_desc: "فحص ثغرات الموقع، شهادات SSL، وبروتوكولات الحماية لحماية متجرك ومستخدميك.",
        sec_btn_text: "افحص الآن",
        radar_card_title: "رادار الإعلانات",
        radar_card_desc: "تحليل صور نتائج الحملات الإعلانية وتكاليف الرسائل للوصول لأعلى عائد ROAS.",
        radar_btn_text: "حلّل حملتك",
        magnet_card_title: "مغناطيس المشاهدات",
        magnet_card_desc: "توليد خطافات (Hooks) جذابة لأول 3 ثوانٍ لفيديوهات الريلز وتيك توك لزيادة الانتشار.",
        magnet_btn_text: "ولّد الخطافات",
        doctor_card_title: "طبيب المبيعات",
        doctor_card_desc: "فحص صفحات الهبوط والمتاجر وتحديد ثغرات عدم التحويل لزيادة نسبة الشراء والمبيعات.",
        doctor_btn_text: "تشخيص متجرك",
        growth_lab: "مختبر النمو",
        growth_lab_title: "مختبر النمو",
        growth_lab_desc: "أدوات ذكية مجانية لفحص أمان موقعك، تحليل إعلاناتك، كتابة هوكات الريلز، وزيادة مبيعاتك.",
        growth_btn: "جرب تحليلات Storm",
        footer_subtitle: "Digital Marketing Solutions",
        footer_desc: "نقدم حلولاً تسويقية شاملة تضمن نمو مبيعاتك",
        footer_services_list: "\"بناء الاستراتيجيات - تصميم المواقع - الإنتاج الإبداعي - الإعلانات وتحليل البيانات\"",
        footer_contact: "تواصل معنا",
        case_studies_title: "دراسات حالة (Case Studies)",
        case_studies_subtitle: "أمثلة حية لنجاحات استراتيجية حققناها لعملائنا بالأرقام والنتائج",
        cs_1_title: "إعادة هيكلة استراتيجية لبراند تجارة إلكترونية",
        cs_1_challenge: "التحدي: ارتفاع تكلفة الاستحواذ على العميل وضعف العائد على الإعلانات.",
        cs_1_solution: "الحل الاستراتيجي: إعادة بناء قمع التسويق واستهداف شرائح جمهور جديدة بدقة.",
        cs_1_result: "النتيجة: زيادة المبيعات بنسبة 180% وتخفيض تكلفة الاستحواذ بنسبة 40%.",
        cs_2_title: "خطة إطلاق منتج جديد في السوق الإقليمي",
        cs_2_challenge: "التحدي: دخول سوق مزدحم بالمنافسين بدون وعي كافٍ بالعلامة التجارية.",
        cs_2_solution: "الحل الاستراتيجي: تنفيذ خطة Go-to-Market شاملة وحملات تشويقية مستهدفة.",
        cs_2_result: "النتيجة: تحقيق المستهدف البيعي للربع الأول خلال أول 3 أسابيع فقط.",
        cs_3_title: "توزيع وتحسين الميزانيات الإعلانية للخدمات",
        cs_3_challenge: "التحدي: إهدار الميزانية على قنوات تسويقية غير فعالة.",
        cs_3_solution: "الحل الاستراتيجي: تحليل بيانات الحملات السابقة وإعادة توجيه الإنفاق للقنوات الأعلى تحويلاً.",
        cs_3_result: "النتيجة: مضاعفة عدد العملاء المحتملين (Leads) بنفس الميزانية الشهرية.",
        cta_strategic: "احصل على استشارتك الاستراتيجية",
        web_main_title: "تصميم وتطوير المواقع وحمايتها",
        web_main_desc: "نصمم ونطور مواقع احترافية سريعة وآمنة بتجربة مستخدم مميزة تعكس هوية علامتك التجارية وتضمن تفاعل عملائك بكفاءة عالية",
        web_card_1_title: "تصميم واجهات المستخدم (UI/UX)",
        web_card_1_desc: "نبتكر تصاميم عصرية ومريحة للعين تضمن سهولة التصفح وتقدم تجربة استثنائية لزوار موقعك",
        web_card_2_title: "تطوير وسرعة الأداء",
        web_card_2_desc: "برمجة نظيفة ومتوافقة مع جميع الأجهزة والشاشات مع تحسين فائق لسرعة التحميل ومحركات البحث (SEO)",
        web_card_3_title: "الحماية والأمان الرقمي",
        web_card_3_desc: "تأمين الموقع ضد الثغرات واختبارات الاختراق لحماية بياناتك وبيانات عملائك بشكل كامل ودائم",
        web_cs_subtitle: "مشاريع مواقع إلكترونية ناجحة أنجزناها لعملائنا بمعايير عالمية",
        web_cs_1_title: "تطوير وتأمين متجر إلكتروني متكامل",
        web_cs_1_challenge: "بطء تصفح المتجر وضعف معدل إتمام عمليات الشراء.",
        web_cs_1_solution: "إعادة هيكلة الواجهة الأمامية بالكامل، تحسين السرعة، وربط بوابات دفع آمنة.",
        web_cs_1_result: "النتيجة: ارتفاع معدل تحويل العملاء بنسبة 140% وتأمين بالكامل ضد الثغرات.",
        web_cs_2_title: "تصميم موقع تعريفي لشركة خدمات كبرى",
        web_cs_2_challenge: "تصميم قديم لا يعكس احترافية الشركة ولا يدعم الهواتف بمرونة.",
        web_cs_2_solution: "تصميم UI/UX مبتكر ومتوافق 100% مع كافة الشاشات مع دعم متعدد اللغات.",
        web_cs_2_result: "النتيجة: مضاعفة عدد الاستفسارات الرسمية عبر الموقع بنسبة تجاوزت 200%.",
        web_cs_3_title: "فحص أمني وتدقيق شامل لموقع منصة تعليمية",
        web_cs_3_challenge: "مخاوف أمنية متكررة واكتشاف ثغرات محتملة تعرض بيانات المستخدمين للخطر.",
        web_cs_3_solution: "إجراء اختبار اختراق شامل، سد الثغرات الحرجة، وتثبيت جدار حماية متقدم.",
        web_cs_3_result: "النتيجة: تأمين المنصة بالكامل بنسبة 100% ومنع أي محاولات اختراق مستقبلية.",
        web_cta_btn: "اطلب استشارتك التسويقية",
        media_main_title: "الإنتاج البصري والمحتوى الإبداعي",
        media_main_desc: "نقدم محتوى مرئي وإبداعي احترافي، تصميم هوية بصرية، مونتاج فيديو، وجلسات تصوير تعزز حضور علامتك التجارية وتجذب جمهورك المستهدف",
        media_card_1_title: "تصميم الهوية البصرية",
        media_card_1_desc: "تصميم شعارات مبتكرة وهوية متكاملة تعكس شخصية وقيم براندك وتترك انطباعاً لا يُنسى",
        media_card_2_title: "إنتاج ومونتاج الفيديو",
        media_card_2_desc: "إخراج ومونتاج فيديوهات تسويقية وإعلانية جذابة لمنصات السوشيال ميديا بخطافات تسرق الانتباه",
        media_card_3_title: "التصوير الاحترافي",
        media_card_3_desc: "جلسات تصوير منتجات وخدمات بجودة استوديو عالية تبرز تفاصيل عملك بدقة واحترافية",
        media_cs_subtitle: "أمثلة حية لنجاحات إبداعية حققناها لعملائنا في الإنتاج المرئي والهوية",
        media_cta_btn: "اطلب استشارتك الإبداعية الآن",
        portfolio: "معرض الأعمال",
        portfolio_btn: "شاهد معرض أعمالنا السابقة",
        ads_main_title: "الإعلانات الممولة والحملات الرقمية",
        ads_main_desc: "ندير حملات إعلانية دقيقة ومدروسة لتحقيق أعلى عائد على الاستثمار (ROI) ومضاعفة مبيعاتك بسرعة",
        ads_card_1_title: "إعلانات منصات ميتا (Meta Ads)",
        ads_card_1_desc: "استهداف دقيق عبر فيسبوك وانستجرام لتحقيق أعلى تفاعل وتحويل الزوار لعملاء حقيقيين",
        ads_card_2_title: "إعلانات جوجل (Google Ads)",
        ads_card_2_desc: "ظهور فوري لمتجرك أو خدمتك أمام العملاء الذين يبحثون عنها بالكلمات المفتاحية المباشرة",
        ads_card_3_title: "إعلانات تيك توك (TikTok Ads)",
        ads_card_3_desc: "حملات فيديو إبداعية تصل للجمهور الشاب وتخلق انتشاراً واسعاً ومبيعات متسارعة",
        ads_card_4_title: "إعلانات سناب شات (Snapchat Ads)",
        ads_card_4_desc: "الوصول لجمهور فعال ومستهلك عبر الإعلانات القصصية والفلترات التفاعلية الجذابة",
        ads_cs_subtitle: "نتائج حية لأرقام وحملات إعلانية ناجحة أدارتها الوكالة لعملائنا",
        ads_cta_btn: "اطلب استشارتك الإعلانية الآن",
        cs_4_title: "حملات جوجل لعلامة تجارية خدمية",
        cs_4_challenge: "التحدي: ضعف الظهور في نتائج محركات البحث أمام المنافسين الأقوياء.",
        cs_4_solution: "الحل الاستراتيجي: حملة بحثية مركزة (Google Search Ads) على الكلمات المستهدفة.",
        cs_4_result: "النتيجة: تصدر نتائج البحث وزيادة طلبات الخدمة بنسبة 140%.",
        data_main_title: "تحليل البيانات وتقارير الأداء",
        data_main_desc: "نحول أرقامك المعقدة إلى تقارير ورؤى واضحة تساعدك على اتخاذ القرارات التسويقية الصحيحة بدقة وتتبع مؤشرات الأداء الرئيسي (KPIs).",
        data_card_1_title: "تتبع مؤشرات الأداء (KPIs)",
        data_card_1_desc: "مراقبة المقاييس الحيوية لحملاتك ونشاطك التجاري لتقييم النجاح وتحديد نقاط التحسين بدقة",
        data_card_2_title: "تقارير العائد على الاستثمار",
        data_card_2_desc: "تحليل مالي دقيق للعائد على الإنفاق الإعلاني (ROAS) لضمان توجيه الميزانيات للقنوات الأكثر ربحية",
        data_card_3_title: "رؤى سلوك المستهلك",
        data_card_3_desc: "فهم رحلة العميل بدقة وعزل الأسباب الكامنة خلف معدلات التحويل والارتداد على موقعك",
        data_cs_subtitle: "كيف ساعد تحليل البيانات الدقيق عملائنا على تحسين الأداء ومضاعفة الأرباح",
        data_cs_1_title: "تحسين قمع المبيعات لمتجر إلكتروني",
        data_cs_1_challenge: "معدل ترك سلة التسوق مرتفع جداً بدون معرفة أسباب مغادرة الزوار.",
        data_cs_1_solution: "تحليل بيانات مسار الشراء بدقة واكتشاف نقاط الاحتكاك ومعالجتها برمجياً وتجربياً.",
        data_cs_1_result: "النتيجة: انخفاض معدل ترك السلة بنسبة 35% وزيادة إتمام الطلبات بنسبة 65%.",
        data_cs_2_title: "إعادة توجيه ميزانيات الإعلانات بالذكاء التحليلي",
        data_cs_2_challenge: "إهدار جزء كبير من الميزانية الإعلانية على قنوات غير مربحة.",
        data_cs_2_solution: "بناء لوحة تحكم متكاملة (Dashboard) لربط مصادر البيانات وتحديد العائد الفعلي لكل قناة.",
        data_cs_2_result: "النتيجة: رفع إجمالي العائد على الإنفاق (ROAS) بنسبة 190%.",
        data_cs_3_title: "توقع سلوك المستهلك وزيادة الاحتفاظ بالعملاء",
        data_cs_3_challenge: "ارتفاع معدل إلغاء الاشتراكات وضياع العملاء الحاليين.",
        data_cs_3_solution: "تحليل الأنماط التاريخية للعملاء لإنشاء نموذج تنبؤي يستهدف العملاء المعرضين للمغادرة.",
        data_cs_3_result: "النتيجة: تقليل معدل خروج العملاء (Churn Rate) بنسبة 45%.",
        data_cta_btn: "اطلب تحليل بياناتك الآن",
        growth_main_title: "ترسانة النتائج ومختبر النمو",
        growth_main_desc: "أدوات ذكية مجانية تم تصميمها خصيصاً لمساعدتك في فحص أمان موقعك، تحليل إعلاناتك بدقة، وكتابة خطافات الريلز لجذب الانتباه ومضاعفة مبيعات متجرك.",
        tool_1_title: "طبيب المبيعات",
        tool_1_desc: "فحص صفحات الهبوط والمتاجر وتحديد ثغرات عدم التحويل لزيادة نسبة الشراء والمبيعات.",
        tool_1_link: "لتشخيص متجرك",
        tool_2_title: "مغناطيس المشاهدات",
        tool_2_desc: "توليد خطافات (Hooks) جذابة لأول 3 ثوان لفيديوهات الريلز وتيك توك لزيادة الانتشار.",
        tool_2_link: "ولد الخطافات",
        tool_3_title: "رادار الإعلانات",
        tool_3_desc: "تحليل صور نتائج الحملات الإعلانية وتكاليف الرسائل للوصول لأعلى عائد ROAS.",
        tool_3_link: "حلل حملتك",
        tool_4_title: "فحص أمان المواقع",
        tool_4_desc: "فحص ثغرات الموقع، شهادات SSL، وبروتوكولات الحماية لحماية متجرك ومستخدميك.",
        tool_4_link: "افحص الآن",
        growth_cta_btn: "اطلب استشارتك الإعلانية الآن",
        audit_title: "فاحص الأمان وحماية صفحات الهبوط",
        audit_desc: "افحص الأمان الإلكتروني، شهادات التشفير، سرعة الصفحة، وعوامل بناء الثقة لزيادة مبيعات متجرك.",
        url_label: "رابط صفحة الهبوط (URL):",
        goal_label: "الهدف الأساسي من الصفحة:",
        goal_default: "اختر الهدف...",
        goal_ecommerce: "بيع منتج مباشر (E-commerce Checkout)",
        goal_lead: "جمع بيانات العملاء (Lead Generation)",
        goal_booking: "حجز استشارة أو موعد (Service Booking)",
        audit_btn: "ابدأ فحص الأمان والأداء الشامل",
        loading_text: "جاري فحص بروتوكولات الحماية والأمان SSL والأكواد...",
        loading_sub: "نختبر كفاءة التشفير، الثقة الرقمية، وسرعة استجابة السيرفر.",
        report_title: "تقرير فحص الحماية والأداء",
        score_label: "مؤشر الأمان والكفاءة: 85 / 100",
        audit_res_1: "1. فحص الحماية والأمان (SSL & Trust): ممتاز، شهادة التشفير مفعلة بنجاح، وبروتوكول HTTPS يعمل بكفاءة تمنع تحذيرات المتصفحات للعملاء.",
        audit_res_2: "2. سرعة التحميل وأداء الأكواد: جيدة جداً، استجابة السيرفر سريعة ولا توجد ملفات ضارة أو سكربتات خارجية تبطئ الصفحة.",
        audit_res_3: "3. وضوح القيمة والشارة الأمنية (Trust Badges): يُنصح بإضافة شعارات الدفع الآمن وسياسة الاسترجاع بجوار زر إتمام الشراء لزيادة معدل تحويل العملاء.",
        re_audit_btn: "فحص صفحة أخرى",
        agency_audit_btn: "اطلب تأمين وتطوير الموقع من الوكالة",
        back_to_lab: "العودة إلى مختبر النمو",
        sales_doc_title: "طبيب المبيعات الذكي",
        sales_doc_desc: "شخص مشكلة مبيعات متجرك واحصل على تشخيص تسويقي فوري وعلاج عملي لزيادة الأرباح.",
        sales_input_label: "ما هي أكبر مشكلة تواجهك في المبيعات حالياً؟",
        sales_btn: "تشخيص مشكلة المبيعات",
        views_mag_title: "مغناطيس المشاهدات والريلز",
        views_mag_desc: "ولد أفكار فيديوهات قصيرة وسكربتات إبداعية لجذب آلاف المشاهدات لعلامتك التجارية.",
        views_input_label: "ما هو مجال منتجك أو خدمتك؟",
        views_btn: "توليد أفكار السكربتات",
        ads_radar_title: "رادار الإعلانات",
        ads_radar_main_title: "رادار تحليل نتائج الإعلانات",
        ads_radar_main_desc: "ارفع سكرين شوت لنتائج حملتك وصورة الإعلان، وسيقوم الذكاء الاصطناعي بتشخيص الأداء، حساب العائد، واكتشاف أسباب ارتفاع التكلفة.",
        radar_platform_label: "المنصة الإعلانية:",
        radar_select_plat: "اختر المنصة...",
        radar_niche_label: "مجال النشاط أو المنتج:",
        radar_niche_placeholder: "مثال: متجر عطور، عقارات، تجارة إلكترونية...",
        radar_summary_label: "نبذة مختصرة عن الإعلان وطريقة استهدافك:",
        radar_summary_placeholder: "اكتب باختصار: هل الإعلان فيديو أم صورة؟ ما هو العرض المقدم؟ وطريقة الاستهداف (جمهور مشدود أم واسع)...",
        radar_metrics_img_label: "سكرين شوت لنتائج الحملة (Metrics):",
        radar_creative_img_label: "سكرين شوت لصورة الإعلان (Creative):",
        radar_submit_btn: "ابدأ تحليل وتشخيص النتائج",
        radar_loading_title: "جاري تحليل أرقام الحملة ومقارنتها بمعايير السوق...",
        radar_loading_desc: "نقرأ بيانات الـ CTR و CPC و ROAS ونحدد نقاط الضعف بدقة.",
        radar_report_title: "تقرير تشخيص أداء الحملة الإعلانية",
        radar_roas_badge: "العائد المتوقع (ROAS): ممتاز (3.4x)",
        radar_res_1: "<strong><i class='fas fa-check-circle'></i> نقاط القوة في النتائج:</strong> نسبة النقر للظهور (CTR) أعلى من متوسط السوق، مما يعني أن التصميم أو الخطاف (Hook) جلب انتباه ممتاز.",
        radar_res_2: "<strong><i class='fas fa-exclamation-triangle'></i> موضع الخلل المكتشف:</strong> تكلفة النقرة (CPC) مرتفعة نسبياً مقارنة بمعدل التحويل (Conversion Rate)، وغالباً المشكلة في بطء صفحة الهبوط أو عدم وضوح زر الشراء.",
        radar_res_3: "<strong><i class='fas fa-bolt'></i> خطة التحسين السريعة:</strong> قم بتعديل الشريحة المستهدفة لتكون أكثر تخصيصاً، وأضف طابع استعجال (Urgency) في نص الإعلان لرفع معدل إتمام الشراء الفوري.",
        radar_reset_btn: "تحليل حملة أخرى",
        radar_whatsapp_btn: "اطلب استشارة لخفض تكلفة الإعلانات",
        audit_page_title: "فحص المواقع",
        audit_url_label: "رابط موقعك (URL):",
        audit_goal_label: "الهدف الأساسي من الصفحة:",
        audit_goal_default: "اختر الهدف...",
        audit_goal_ecommerce: "بيع منتج مباشر (E-commerce Checkout)",
        audit_goal_lead: "جمع بيانات العملاء (Lead Generation)",
        audit_goal_booking: "حجز استشارة أو موعد (Service Booking)",
        audit_submit_btn: "ابدأ فحص الأمان والأداء الشامل",
        audit_loading_title: "جاري فحص بروتوكولات الحماية والأمان SSL والأكواد...",
        audit_loading_desc: "نختبر كفاءة التشفير، الثقة الرقمية، وسرعة استجابة السيرفر.",
        audit_report_title: "تقرير فحص الحماية والأداء",
        audit_score: "مؤشر الأمان والكفاءة: 85 / 100",
        audit_res_1: "<strong>1. فحص الحماية والأمان (SSL & Trust):</strong> ممتاز، شهادة التشفير مفعلة بنجاح، وبروتوكول HTTPS يعمل بكفاءة تمنع تحذيرات المتصفحات للعملاء.",
        audit_res_2: "<strong>2. سرعة التحميل وأداء الأكواد:</strong> جيدة جداً، استجابة السيرفر سريعة ولا توجد ملفات ضارة أو سكربتات خارجية تبطئ الصفحة.",
        audit_res_3: "<strong>3. وضوح القيمة والشارة الأمنية (Trust Badges):</strong> يُنصح بإضافة شعارات الدفع الآمن وسياسة الاسترجاع بجوار زر إتمام الشراء لزيادة معدل تحويل العملاء.",
        audit_reset_btn: "فحص صفحة أخرى",
        audit_whatsapp_btn: "اطلب تأمين وتطوير الموقع من الوكالة",
        back_to_lab_btn: "العودة إلى مختبر النمو",
        store_url_label: "رابط المتجر أو صفحة الهبوط:",
        store_type_label: "طبيعة النشاط التجاري (إدخال حر):",
        sales_submit_btn: "ابدأ التشخيص والفحص الشامل",
        sales_loading_title: "جاري فحص المتجر وتحليل تجربة المستخدم...",
        sales_loading_desc: "نبحث عن ثغرات أزرار الشراء، سرعة التحميل، ونقاط التسرب.",
        sales_report_title: "تقرير فحص وتشخيص المتجر",
        sales_score: "كفاءة المتجر: 68%",
        sales_res_1: "ثغرة حرجة مكتشفة: زر 'أضف للسلة' يفتقر إلى التباين اللوني القوي، مما يقلل من نسبة نقر العملاء (CTR) بمتوسط 14%.",
        sales_res_2: "ملاحظة الأداء والسرعة: زمن استجابة صفحة الهبوط يتجاوز 3.2 ثانية، وهو ما يؤدي لخروج ما يقارب 30% من زوار الإعلانات.",
        sales_res_3: "توصية طبيب المبيعات: إضافة آراء العملاء الحقيقية (Social Proof) مباشرة تحت السعر لزيادة معدل الثقة ومضاعفة المبيعات.",
        sales_whatsapp_btn: "اطلب جلسة إصلاح المتجر مع خبرائنا",
        views_magnet_title: "مغناطيس المشاهدات الذكي",
        views_magnet_desc: "ولد خطاطيف (Hooks) وبدايات فيديو تخطف انتباه المشاهد في أول 3 ثوانٍ وتضمن لك أعلى معدلات احتفاظ ومشاهدة على تيك توك وريلز.",
        hook_topic_label: "موضوع الفيديو أو المنتج (إدخال حر):",
        target_audience_label: "الجمهور المستهدف:",
        hook_submit_btn: "توليد خطاطيف جذب الانتباه",
        hook_loading_title: "جاري صياغة خطاطيف قوية ومؤثرة...",
        hook_loading_desc: "نحلل أنماط المشاهدة العالية لنصنع لك بدايات لا تقاوم.",
        hook_report_title: "الخطاطيف المقترحة لفيديوك",
        hook_badge: "أول 3 ثوانٍ حاسمة",
        hook_res_1: "1. خطاف الصدمة والفضول: \"لو بتصرف فلوسك على الإعلانات بالطريقة دي، فانت بتخسر 50% من ميزانيتك من غير ما تحس!\"",
        hook_res_2: "2. خطاف كسر المعتقدات: \"كل اللوكال ماركتس فاكرين إن السعر الرخيص هو اللي بيبيع، والواقع عكس كده تماماً...\"",
        hook_res_3: "3. خطاف التحدي المباشر: \"تحدي! جرب الطريقة دي في أول فيديو جاي عندك وشوف بنفسك إزاي المشاهدات هتتضاعف.\"",
        hook_reset_btn: "توليد خطاطيف جديدة",
        hook_whatsapp_btn: "اطلب استراتيجية محتوى متكاملة",
        portfolio_img_meta1: "حملات ميتا",
        portfolio_desc_meta1: "أداء استثنائي وتوليد تفاعل منخفض التكلفة.",
        portfolio_img_meta2: "حملات ميتا",
        portfolio_desc_meta2: "تحقيق أعلى عائد على الإنفاق الإعلاني ROAS.",
        portfolio_img_meta3: "حملات ميتا",
        portfolio_desc_meta3: "استهداف دقيق وتحسين مستمر للنتائج.",
        portfolio_img_meta4: "ملخص أداء الحملات",
        portfolio_desc_meta4: "إحصائيات متكاملة ومتابعة دقيقة للأداء.",
        portfolio_img_tiktok1: "حملات تيك توك",
        portfolio_desc_tiktok1: "إدارة ميزانيات واحترافية في تحقيق الانتشار.",
        portfolio_img_tiktok2: "حملات تيك توك",
        portfolio_desc_tiktok2: "تحقيق نتائج مباشرة ومعدلات تحويل عالية.",
        portfolio_img_alpha: "الفا الكتريك",
        portfolio_desc_alpha: "تصميم هندسي إبداعي للتركيبات الصناعية.",
        portfolio_img_zain_offer: "عروض زين 5G",
        portfolio_desc_zain_offer: "تصميم تسويقي ترويجي لباقات الإنترنت.",
        portfolio_img_mobily: "عروض موبايلي",
        portfolio_desc_mobily: "إعلان ترويجي لسرعات الإنترنت والخصومات.",
        portfolio_img_clear: "كلير سكالب",
        portfolio_desc_clear: "تصميم إعلاني طبيعي واحترافي لمنتجات العناية.",
        portfolio_img_ingezny: "خدمات إنجزني",
        portfolio_desc_ingezny: "تصميم هوية لخدمات التوصيل السريع والشحن.",
        portfolio_vid_edu: "فيديو تعليمي",
        portfolio_desc_edu: "إنتاج مرئي وإبداعي يعكس خدمات الوكالة.",
        portfolio_vid_watches: "اعلان القصر الملكي",
        portfolio_desc_watches: "إنتاج مرئي يعكس قيمة الساعات السويسرية.",
        portfolio_vid_zain5g: "باقات زين 5G المنزلية",
        portfolio_desc_zain5g: "إنتاج مرئي يعكس سرعة الإنترنت وأهميته.",
        portfolio_vid_clear_ad: "اعلان Clear Scalp",
        portfolio_desc_clear_ad: "إنتاج مرئي يعكس جودة وأهمية المنتج.",
        portfolio_vid_restaurant: "اعلان مطعم مأكلات تركية",
        portfolio_desc_restaurant: "إنتاج مرئي يعكس جودة الطعم والخدمة.",
        portfolio_vid_fashion: "اعلان ملابس",
        portfolio_desc_fashion: "إنتاج مرئي يعكس جودة الخامات وجمال التفصيل.",
        portfolio_web_zain: "Zain-5G",
        portfolio_desc_zain: "تطوير صفحة تفاعلية لزيادة معدلات التحويل.",
        portfolio_web_watches: "Watches-Buyers",
        portfolio_desc_watches_web: "موقع إلكتروني لفحص وتقييم وشراء الساعات.",
        visit_site_btn: "زيارة الموقع"
    },
    en: {
        home: "Home",
        services: "Services",
        strategies: "Marketing Strategies",
        web: "Web Design",
        media: "Production & Creative",
        ads: "Advertising",
        data: "Data Analysis",
        hero_title: "Storm Agency",
        hero_tagline: "Your ultimate partner in brand building and digital marketing",
        services_title: "Our Services",
        strategies_title: "Marketing Strategies & Planning",
        strategies_desc: "We build comprehensive marketing strategies that help your clients reach their target audience and achieve their marketing goals",
        web_title: "Website Design, Development & Security",
        web_desc: "We design and develop professional, fast, and secure websites with exceptional user experience that reflects your brand identity",
        media_title: "Photography, Production & Graphic Design",
        media_desc: "We provide professional photography services and creative visual content that attracts audience attention and reflects your brand quality",
        ads_title: "Advertising",
        ads_desc: "We plan and execute effective advertising campaigns across all platforms to maximize your advertising ROI",
        data_title: "Data Analysis",
        data_desc: "We analyze your campaign data and audience behavior to make informed marketing decisions and continuously improve your campaign performance",
        view_work: "Our Work",
        about_title: "About Us",
        about_desc: "Storm Agency is a leading marketing and advertising agency providing comprehensive marketing solutions for businesses and brands",
        contact_title: "Contact Us",
        footer: "© 2026 Storm Agency. All rights reserved",
        read_more: "Read More",
        whatsapp: "WhatsApp Us",
        follow_us: "Follow Us",
        strategies_1: "Market & Competitor Analysis",
        strategies_1_desc: "Comprehensive study of market requirements and competitor behavior",
        strategies_2: "Marketing Plan Development",
        strategies_2_desc: "Defining objectives, strategies, and appropriate marketing channels",
        strategies_3: "Campaign Management",
        strategies_3_desc: "Executing and monitoring marketing campaigns and measuring performance",
        web_1: "UI/UX Design",
        web_1_desc: "Attractive and easy-to-use user interfaces",
        web_2: "Website Development",
        web_2_desc: "Programming the website with the latest technologies and highest quality standards",
        web_3: "Security & Protection",
        web_3_desc: "Protecting the website from hacks and cyber threats",
        media_1: "Professional Photography",
        media_1_desc: "High-quality product and business photography",
        media_2: "Visual Production",
        media_2_desc: "Producing creative videos and visual advertisements",
        media_3: "Graphic Design",
        media_3_desc: "Designing visual identities and professional print materials",
        ads_1: "Google Ads",
        ads_1_desc: "Advertising campaigns on search and display networks",
        ads_2: "Social Media Ads",
        ads_2_desc: "Targeted ads on Facebook, Instagram, and Twitter",
        ads_3: "Video Ads",
        ads_3_desc: "Producing and publishing engaging video advertisements",
        data_1: "Website Analytics",
        data_1_desc: "Measuring website performance and visitor behavior",
        data_2: "Campaign Analysis",
        data_2_desc: "Evaluating ROI on advertising campaigns",
        data_3: "Reports & Reviews",
        data_3_desc: "Detailed reports and continuous improvement exercises",
        word1: "Strategy",
        word2: "Creativity",
        word3: "Marketing",
        word4: "Design",
        word5: "Analysis",
        word6: "Advertising",
        word7: "Digital",
        word8: "Success",
        portfolio_subtitle: "Samples of our outstanding work",
        portfolio_desc: "Samples of our outstanding work that we are proud of. We work with passion and creativity to provide the best marketing solutions for our clients.",
        all_work: "All Our Work",
        view_all: "View All Work",
        cta_consultation: "Get Your Free Consultation",
        stats_budget_desc: "Successfully Managed Ad Budgets",
        stats_campaigns_desc: "Successful Ad Campaigns",
        stats_impressions_desc: "Ad Impressions & Reach",
        stats_messages_desc: "Direct Messages & Inquiries",
        partners_title: "Success Partners",
        scanner_title: "Website Security Audit",
        scanner_desc: "Comprehensive audit to detect website security vulnerabilities",
        results_arsenal_title: "Results Arsenal",
        results_arsenal_desc: "Free AI tools to audit site security, analyze ad campaigns, generate viral hooks, and boost your sales.",
        back_to_home: "Back to Home",
        arsenal_header_desc: "Free AI tools to audit site security, analyze ad campaigns, generate viral hooks, and boost your sales.",
        sec_card_title: "Website Security Audit",
        sec_card_desc: "Scan vulnerabilities, SSL certificates, and security protocols to protect your store.",
        sec_btn_text: "Audit Now",
        radar_card_title: "Ad Radar",
        radar_card_desc: "Analyze ad campaign screenshots and CPL metrics to maximize your ROAS.",
        radar_btn_text: "Analyze Ads",
        magnet_card_title: "View Magnet",
        magnet_card_desc: "Generate viral 3-second hooks for Reels and TikTok to double your reach.",
        magnet_btn_text: "Generate Hooks",
        doctor_card_title: "Sales Doctor",
        doctor_card_desc: "Diagnose landing pages and store leaks to increase conversion rates and sales.",
        doctor_btn_text: "Diagnose Your Store",
        growth_lab: "Growth Lab",
        growth_lab_title: "Growth Lab",
        growth_lab_desc: "Free smart tools to scan your website security, analyze ads, write reel hooks, and boost your sales.",
        growth_btn: "Try Storm Analytics",
        footer_subtitle: "Digital Marketing Solutions",
        footer_desc: "We provide comprehensive marketing solutions to ensure your sales growth",
        footer_services_list: "\"Strategy Building - Web Design - Creative Production - Ads & Data Analytics\"",
        footer_contact: "Contact Us",
        case_studies_title: "Case Studies",
        case_studies_subtitle: "Real examples of strategic successes we achieved for our clients with numbers and results",
        cs_1_title: "Strategic Restructuring for an E-Commerce Brand",
        cs_1_challenge: "Challenge: High customer acquisition cost (CAC) and low ad return.",
        cs_1_solution: "Strategic Solution: Rebuilding the marketing funnel and targeting new audience segments precisely.",
        cs_1_result: "Result: 180% increase in sales and 40% reduction in acquisition cost.",
        cs_2_title: "Regional Market New Product Launch Plan",
        cs_2_challenge: "Challenge: Entering a crowded market without sufficient brand awareness.",
        cs_2_solution: "Strategic Solution: Implementing a comprehensive Go-to-Market plan and targeted teaser campaigns.",
        cs_2_result: "Result: Achieving the Q1 sales target within just the first 3 weeks.",
        cs_3_title: "Budget Allocation & Optimization for Services",
        cs_3_challenge: "Challenge: Wasting budget on inefficient marketing channels.",
        cs_3_solution: "Strategic Solution: Analyzing past campaign data and redirecting spending to high-converting channels.",
        cs_3_result: "Result: Doubling the number of leads with the same monthly budget.",
        cta_strategic: "Get Your Strategic Consultation",
        web_main_title: "Website Design, Development & Security",
        web_main_desc: "We design and develop professional, fast, and secure websites with an exceptional user experience that reflects your brand identity",
        web_card_1_title: "UI/UX Design",
        web_card_1_desc: "We create modern and eye-friendly designs ensuring smooth navigation and an exceptional visitor experience",
        web_card_2_title: "Development & Performance Speed",
        web_card_2_desc: "Clean code compatible with all devices and screens, with superior loading speed and SEO optimization",
        web_card_3_title: "Digital Security & Protection",
        web_card_3_desc: "Securing your website against vulnerabilities and penetration tests to fully protect your data and customers' data",
        web_cs_subtitle: "Successful website projects delivered for our clients with global standards",
        web_cs_1_title: "Full E-Commerce Store Development & Security",
        web_cs_1_challenge: "Slow store browsing and low checkout completion rate.",
        web_cs_1_solution: "Complete frontend restructuring, speed optimization, and secure payment gateways integration.",
        web_cs_1_result: "Result: 140% increase in customer conversion rate and full security against vulnerabilities.",
        web_cs_2_title: "Corporate Profile Website Design",
        web_cs_2_challenge: "Old design failing to reflect corporate professionalism or support mobile responsiveness.",
        web_cs_2_solution: "Innovative UI/UX design 100% compatible with all screens with multi-language support.",
        web_cs_2_result: "Result: Doubling official inquiries through the website by over 200%.",
        web_cs_3_title: "Security Audit & Comprehensive Check for an EdTech Platform",
        web_cs_3_challenge: "Recurrent security concerns and potential vulnerabilities risking user data.",
        web_cs_3_solution: "Performing a comprehensive penetration test, patching critical vulnerabilities, and installing an advanced firewall.",
        web_cs_3_result: "Result: 100% platform security and prevention of future breach attempts.",
        web_cta_btn: "Request Your Marketing Consultation",
        media_main_title: "Visual Production & Creative Content",
        media_main_desc: "We deliver professional visual and creative content, brand identity design, video editing, and photoshoots that boost your brand presence",
        media_card_1_title: "Visual Identity Design",
        media_card_1_desc: "Designing innovative logos and a cohesive identity reflecting your brand's personality and values",
        media_card_2_title: "Video Production & Editing",
        media_card_2_desc: "Directing and editing engaging promotional videos for social media with attention-grabbing hooks",
        media_card_3_title: "Professional Photography",
        media_card_3_desc: "Studio-quality product and service photography highlighting every detail with precision",
        media_cs_subtitle: "Live examples of creative successes we achieved for our clients in visual production and branding",
        media_cta_btn: "Request Your Creative Consultation Now",
        portfolio: "Portfolio",
        portfolio_btn: "View Our Past Work",
        ads_main_title: "Paid Advertising & Digital Campaigns",
        ads_main_desc: "We manage precise, well-thought-out ad campaigns to achieve the highest ROI and rapidly multiply your sales",
        ads_card_1_title: "Meta Ads",
        ads_card_1_desc: "Precise targeting via Facebook and Instagram to drive high engagement and convert visitors into real customers",
        ads_card_2_title: "Google Ads",
        ads_card_2_desc: "Immediate visibility for your store or service in front of customers searching directly via keywords",
        ads_card_3_title: "TikTok Ads",
        ads_card_3_desc: "Creative video campaigns reaching young audiences, creating widespread exposure and fast sales",
        ads_card_4_title: "Snapchat Ads",
        ads_card_4_desc: "Reaching an active consumer audience through storytelling ads and engaging interactive filters",
        ads_cs_subtitle: "Live results of successful ad campaigns managed by the agency for our clients",
        ads_cta_btn: "Request Your Ad Consultation Now",
        cs_4_title: "Google Campaigns for a Service Brand",
        cs_4_challenge: "Challenge: Low search engine visibility against strong competitors.",
        cs_4_solution: "Strategic Solution: Focused Google Search Ads campaign targeting key search terms.",
        cs_4_result: "Result: Dominating search results and increasing service requests by 140%.",
        data_main_title: "Data Analysis & Performance Reports",
        data_main_desc: "We turn complex numbers into clear reports and insights to help you make accurate marketing decisions and track KPIs.",
        data_card_1_title: "KPI Tracking",
        data_card_1_desc: "Monitoring vital metrics of your campaigns and business activity to evaluate success and pinpoint improvements",
        data_card_2_title: "ROI Reports",
        data_card_2_desc: "Precise financial analysis of Return on Ad Spend (ROAS) to ensure budgets target profitable channels",
        data_card_3_title: "Consumer Behavior Insights",
        data_card_3_desc: "Understanding the customer journey precisely and isolating reasons behind conversion and bounce rates",
        data_cs_subtitle: "How precise data analysis helped our clients improve performance and multiply profits",
        data_cs_1_title: "E-Commerce Funnel Optimization",
        data_cs_1_challenge: "Extremely high cart abandonment rate without knowing exit reasons.",
        data_cs_1_solution: "Analyzing purchase funnel data precisely, detecting friction points, and fixing them programmatically.",
        data_cs_1_result: "Result: 35% drop in cart abandonment and 65% increase in completed orders.",
        data_cs_2_title: "Ad Budget Redirection via Analytical AI",
        data_cs_2_challenge: "Wasting a large chunk of ad budget on unprofitable channels.",
        data_cs_2_solution: "Building an integrated dashboard to connect data sources and determine actual returns per channel.",
        data_cs_2_result: "Result: Raising total ROAS by 190%.",
        data_cs_3_title: "Predicting Consumer Behavior & Increasing Retention",
        data_cs_3_challenge: "High churn rate and loss of existing customers.",
        data_cs_3_solution: "Analyzing historical customer patterns to build a predictive model targeting at-risk churners.",
        data_cs_3_result: "Result: Reducing customer churn rate by 45%.",
        data_cta_btn: "Request Your Data Analysis Now",
        growth_main_title: "Results Arsenal & Growth Lab",
        growth_main_desc: "Free smart tools designed specifically to help you scan your site security, analyze ads, write reel hooks, and multiply sales.",
        tool_1_title: "Sales Doctor",
        tool_1_desc: "Diagnose landing pages and stores, identify conversion bottlenecks to boost purchases.",
        tool_1_link: "Diagnose Store",
        tool_2_title: "Views Magnet",
        tool_2_desc: "Generate viral 3-second hooks for Reels and TikTok to maximize reach.",
        tool_2_link: "Generate Hooks",
        tool_3_title: "Ad Radar",
        tool_3_desc: "Analyze ad campaign screenshots and messaging costs to achieve highest ROAS.",
        tool_3_link: "Analyze Ads",
        tool_4_title: "Website Security Audit",
        tool_4_desc: "Scan site vulnerabilities, SSL certificates, and security protocols.",
        tool_4_link: "Audit Now",
        growth_cta_btn: "Request Your Ad Consultation Now",
        audit_title: "Landing Page Security & Protection Auditor",
        audit_desc: "Audit digital security, encryption certificates, page speed, and trust factors.",
        url_label: "Landing Page URL:",
        goal_label: "Primary Page Goal:",
        goal_default: "Select goal...",
        goal_ecommerce: "Direct Product Checkout (E-commerce)",
        goal_lead: "Lead Generation",
        goal_booking: "Service Booking / Appointment",
        audit_btn: "Start Comprehensive Security & Performance Audit",
        loading_text: "Checking SSL security protocols and scripts...",
        loading_sub: "Testing encryption efficiency, digital trust, and server response speed.",
        report_title: "Security & Performance Audit Report",
        score_label: "Security & Efficiency Index: 85 / 100",
        audit_res_1: "1. Security & Trust Audit (SSL): Excellent, encryption active, HTTPS working efficiently.",
        audit_res_2: "2. Load Speed & Code Performance: Very good, fast server response with no malicious scripts.",
        audit_res_3: "3. Value Clarity & Trust Badges: Recommended to add secure payment badges near checkout.",
        re_audit_btn: "Audit Another Page",
        agency_audit_btn: "Request Site Security & Dev from Agency",
        back_to_lab: "Back to Growth Lab",
        sales_doc_title: "Smart Sales Doctor",
        sales_doc_desc: "Diagnose your store's sales problem and get an instant marketing diagnosis.",
        sales_input_label: "What is your biggest sales challenge right now?",
        sales_btn: "Diagnose Sales Issue",
        views_mag_title: "Views & Reels Magnet",
        views_mag_desc: "Generate short video ideas and creative scripts to attract thousands of views.",
        views_input_label: "What is your product or service niche?",
        views_btn: "Generate Script Ideas",
        ads_radar_title: "Ad Radar",
        ads_radar_main_title: "Ad Results Radar Analysis",
        ads_radar_main_desc: "Upload screenshots of your campaign results and ad creative for AI diagnosis.",
        radar_platform_label: "Advertising Platform:",
        radar_select_plat: "Select platform...",
        radar_niche_label: "Business or Product Niche:",
        radar_niche_placeholder: "Example: Perfume store, Real estate, E-commerce...",
        radar_summary_label: "Brief overview of the ad and targeting method:",
        radar_summary_placeholder: "Write briefly: Video or image ad? Offer? Targeting strategy...",
        radar_metrics_img_label: "Campaign Results Screenshot (Metrics):",
        radar_creative_img_label: "Ad Creative Screenshot (Creative):",
        radar_submit_btn: "Start Results Analysis & Diagnosis",
        radar_loading_title: "Analyzing campaign numbers and comparing with market benchmarks...",
        radar_loading_desc: "Reading CTR, CPC, and ROAS data to pinpoint weaknesses.",
        radar_report_title: "Ad Campaign Performance Diagnosis Report",
        radar_roas_badge: "Expected ROAS: Excellent (3.4x)",
        radar_res_1: "<strong><i class='fas fa-check-circle'></i> Strengths:</strong> CTR higher than market average, meaning design or hook grabbed attention.",
        radar_res_2: "<strong><i class='fas fa-exclamation-triangle'></i> Identified Flaw:</strong> CPC is relatively high compared to conversion rate, likely due to slow landing page.",
        radar_res_3: "<strong><i class='fas fa-bolt'></i> Quick Improvement Plan:</strong> Refine target audience segment and add urgency in ad copy.",
        radar_reset_btn: "Analyze Another Campaign",
        radar_whatsapp_btn: "Request Ad Cost Reduction Consultation",
        audit_page_title: "Website Audit",
        audit_url_label: "Your Website URL:",
        audit_goal_label: "Primary Page Goal:",
        audit_goal_default: "Select goal...",
        audit_goal_ecommerce: "Direct Product Checkout (E-commerce)",
        audit_goal_lead: "Lead Generation",
        audit_goal_booking: "Service Booking / Appointment",
        audit_submit_btn: "Start Comprehensive Security & Performance Audit",
        audit_loading_title: "Checking SSL security protocols and scripts...",
        audit_loading_desc: "Testing encryption efficiency, digital trust, and server response speed.",
        audit_report_title: "Security & Performance Audit Report",
        audit_score: "Security & Efficiency Index: 85 / 100",
        audit_res_1: "<strong>1. Security & Trust (SSL):</strong> Excellent, encryption active and HTTPS running smoothly.",
        audit_res_2: "<strong>2. Load Speed & Code:</strong> Very good, fast server response.",
        audit_res_3: "<strong>3. Trust Badges:</strong> Recommended to add secure checkout badges.",
        audit_reset_btn: "Audit Another Page",
        audit_whatsapp_btn: "Request Security & Development from Agency",
        back_to_lab_btn: "Back to Growth Lab",
        store_url_label: "Store or Landing Page URL:",
        store_type_label: "Business Nature:",
        sales_submit_btn: "Start Comprehensive Diagnosis",
        sales_loading_title: "Scanning store and analyzing UX...",
        sales_loading_desc: "Looking for cart bottlenecks and load speed issues.",
        sales_report_title: "Store Diagnosis Report",
        sales_score: "Store Efficiency: 68%",
        sales_res_1: "Critical vulnerability: 'Add to Cart' button lacks strong contrast.",
        sales_res_2: "Performance note: Landing page load time exceeds 3.2 seconds.",
        sales_res_3: "Doctor recommendation: Add genuine social proof directly under price.",
        sales_whatsapp_btn: "Request Store Fix Session with Experts",
        views_magnet_title: "Smart Views Magnet",
        views_magnet_desc: "Generate powerful hooks for TikTok and Reels to secure high retention.",
        hook_topic_label: "Video Topic or Product:",
        target_audience_label: "Target Audience:",
        hook_submit_btn: "Generate Attention Hooks",
        hook_loading_title: "Crafting powerful hooks...",
        hook_loading_desc: "Analyzing high-view patterns to build irresistible openings.",
        hook_report_title: "Suggested Video Hooks",
        hook_badge: "First 3 Seconds Matter",
        hook_res_1: "1. Shock & Curiosity Hook: \"If you spend money on ads this way, you're losing 50% of your budget!\"",
        hook_res_2: "2. Belief-Breaking Hook: \"Every local market thinks cheap price sells, but reality is totally different...\"",
        hook_res_3: "3. Direct Challenge Hook: \"Challenge! Try this method in your next video and watch views multiply.\"",
        hook_reset_btn: "Generate New Hooks",
        hook_whatsapp_btn: "Request Full Content Strategy",
        portfolio_img_meta1: "Meta Campaigns",
        portfolio_desc_meta1: "Exceptional performance and low-cost engagement.",
        portfolio_img_meta2: "Meta Campaigns",
        portfolio_desc_meta2: "Achieving highest ROAS on ad spend.",
        portfolio_img_meta3: "Meta Campaigns",
        portfolio_desc_meta3: "Precise targeting and continuous optimization.",
        portfolio_img_meta4: "Campaign Performance Summary",
        portfolio_desc_meta4: "Integrated stats and meticulous performance tracking.",
        portfolio_img_tiktok1: "TikTok Campaigns",
        portfolio_desc_tiktok1: "Professional budget management and reach generation.",
        portfolio_img_tiktok2: "TikTok Campaigns",
        portfolio_desc_tiktok2: "Direct results and high conversion rates.",
        portfolio_img_alpha: "Alpha Electric",
        portfolio_desc_alpha: "Creative engineering design for industrial installations.",
        portfolio_img_zain_offer: "Zain 5G Offers",
        portfolio_desc_zain_offer: "Promotional marketing design for internet packages.",
        portfolio_img_mobily: "Mobily Offers",
        portfolio_desc_mobily: "Promotional ad for internet speeds and discounts.",
        portfolio_img_clear: "Clear Scalp",
        portfolio_desc_clear: "Natural, professional ad design for care products.",
        portfolio_img_ingezny: "Ingezny Services",
        portfolio_desc_ingezny: "Identity design for express delivery and shipping services.",
        portfolio_vid_edu: "Educational Video",
        portfolio_desc_edu: "Visual and creative production reflecting agency services.",
        portfolio_vid_watches: "Royal Palace Ad",
        portfolio_desc_watches: "Visual production reflecting Swiss watch value.",
        portfolio_vid_zain5g: "Zain 5G Home Packages",
        portfolio_desc_zain5g: "Visual production reflecting internet speed and importance.",
        portfolio_vid_clear_ad: "Clear Scalp Ad",
        portfolio_desc_clear_ad: "Visual production highlighting product quality.",
        portfolio_vid_restaurant: "Turkish Restaurant Ad",
        portfolio_desc_restaurant: "Visual production reflecting taste and service quality.",
        portfolio_vid_fashion: "Fashion Ad",
        portfolio_desc_fashion: "Visual production reflecting fabric quality and details.",
        portfolio_web_zain: "Zain-5G",
        portfolio_desc_zain: "Developing an interactive page to boost conversion rates.",
        portfolio_web_watches: "Watches-Buyers",
        portfolio_desc_watches_web: "Website for auditing, valuing, and buying luxury watches.",
        visit_site_btn: "Visit Website"
    }
};

// ==========================================
// 2. دالة تغيير وتطبيق اللغة الشاملة
// ==========================================
function setLanguage(lang) {
    // التأكد من دعم اللغة الممررة
    if (!translations[lang]) lang = 'ar';

    // حفظ اللغة في المتصفح
    localStorage.setItem('lang', lang);
    localStorage.setItem('selected_lang', lang);
    
    // ضبط سمات الاتجاه واللغة لعنصر الجذر
    document.documentElement.setAttribute('lang', lang);
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    
    // تحديث النصوص التي تحتوي على سمة data-i18n
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    // تحديث حالات الـ Active للقائمة المنسدلة للغة إن وجدت
    document.querySelectorAll('.lang-option').forEach(opt => {
        opt.classList.toggle('active', opt.dataset.lang === lang);
    });

    const currentLangEl = document.querySelector('.current-lang');
    if (currentLangEl) {
        const langNames = { ar: 'العربية', en: 'English' };
        currentLangEl.textContent = langNames[lang] || lang;
    }
}

// ==========================================
// 3. تهيئة الواجهة والأحداث عند اكتمال التحميل
// ==========================================
document.addEventListener('DOMContentLoaded', () => {
    // استرجاع اللغة المحفوظة أو البدء بالعربية افتراضياً
    const savedLang = localStorage.getItem('lang') || localStorage.getItem('selected_lang') || 'ar';
    setLanguage(savedLang);

    // تفعيل قائمة تغيير اللغة المنسدلة بأمان دون كسر بقية القوائم
    const langBtn = document.querySelector('.lang-btn');
    const langDropdown = document.querySelector('.lang-dropdown');

    if (langBtn && langDropdown) {
        langBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            langDropdown.classList.toggle('show');
        });

        document.addEventListener('click', () => {
            langDropdown.classList.remove('show');
        });
    }

    // ربط ضغط خيارات اللغة بتنفيذ دالة التغيير وتحديث الصفحة
    document.querySelectorAll('.lang-option').forEach(option => {
        option.addEventListener('click', (e) => {
            const selectedLang = e.currentTarget.getAttribute('data-lang');
            if (selectedLang) {
                setLanguage(selectedLang);
                window.location.reload();
            }
        });
    });
});